services:
  pioneer_bringup:
    build: ../src/pionner_bringup
    profiles: ["pionner"]
    network_mode: host
    command: /bin/bash
    privileged: true
    tty: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    env_file:
      - ./bringup.env

  realsense2_camera_bringup:
    build: ../src/realsense2_camera_bringup
    profiles: ["realsense2"]
    network_mode: host
    command: /bin/bash
    privileged: true
    tty: true
    devices:
      - "/dev:/dev"
    env_file:
      - ./bringup.env

  livox_bringup:
    build: ../src/livox_bringup
    profiles: ["livox"]
    network_mode: host
    command: /bin/bash
    privileged: true
    tty: true
    devices:
      - "/dev:/dev"
    env_file:
      - ./bringup.env

  fastlio2_bringup:
    build: ../src/fastlio2_bringup
    profiles: ["fastlio2"]
    network_mode: host
    command: /bin/bash
    privileged: true
    tty: true
    devices:
      - "/dev:/dev"
    env_file:
      - ./bringup.env
    environment:
      CONFIG_FILE: "avia.yaml"
